# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Ruby version
AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'storage/**/*'

# Overwrite or add rules to create your own house style
#
# Allow longer lines in config files
Layout/LineLength:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
